name: build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar Buildozer .spec
      run: |
        pip install buildozer
        buildozer init
        sed -i 's/title = My Application/title = Para Valentina/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd,pillow/' buildozer.spec
        sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec

    - name: Compilar APK con Github Action oficial
      uses: ArtemGovorov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Subir Artefacto APK
      uses: actions/upload-artifact@v4
      with:
        name: app-valentina
        path: bin/*.apk
